language: python

#Slack notifications!
#we always want notifications if build fails
#we only want success notifications if change
notifications:
  email: false
  slack:
    secure: OabV2i2WfC75kuU/zJORf59OlC0r2/yFhqStthhNsHksK74IdVwDR3+0+9187JhYUHyJwCSOK9pYYrGtboyD34O7/MglIoAxR0GP79RgQAxemEpXSsEYpnnl7zHCZeZ+AgMD93p6TqnM9bNOSqNjQb7DtcaYwiIApAZHCecsT+FqtCY1HVFdiLprt7pUL1nM/dVi1VQkyJ+9DKye4cUHcJe8wj5DvwGYCMO7hPn3BKDlJoJ2YqgIGRVFiTNjdWGDSjf79LO2H8VacZe2A+eckQsuLqh/gpM5j+ekHoi2pMA+obc81RQPkWz+x1g9tlt/N+bBMt8CJ4Z0XoJfjTTzgwxAsTDqUIxIMkEuvi7QUvUP1+47DhzSNGf8od6NIjggd+TWaOj8UOwphvLL9VdjB4kX3JFy0sWXpBSngp/o5VPg430hnWMQU7y14SnfVUg4eN/LI+LMydAx3IZZeOMgLH6EA02WuB0syKZRyKZtV5tPQkbcic9qJu+bo4xwFIlXZ6YOvW+CImEkne5hc83GJ4ajvH69BXY2DnKOLGCtz5U/d89YKBLo7oCFGKD4j3MRbTYySNL0kZSrFSEFQTi0WbFmJWSc5kpWuPHa5Ud3ozPMnsPNRDM2sXhPB9RvsUWIUIOnDEkDt7V77Ujwi2VSUqY0JBA0EJkKol5y/Bfx2Ys=
    on_success: change
    on_failure: always


#compile all python files
script:
  - python -m py_compile attendance-website/autoLogout.py
  - python -m py_compile attendance-website/manage.py
  - python -m py_compile attendance-website/attendance/urls.py
  - python -m py_compile attendance-website/attendance/wsgi.py
  - python -m py_compile attendance-website/attendance/settings.py
  - python -m py_compile attendance-website/attendanceapp/admin.py
  - python -m py_compile attendance-website/attendanceapp/models.py
  - python -m py_compile attendance-website/attendanceapp/tests.py
  - python -m py_compile attendance-website/attendanceapp/views.py
